[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# 重映射配置
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@pancakeswap/=lib/pancake-smart-contracts/projects/exchange-protocol/"
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
bsc = "${BSC_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ARBISCAN_KEY}" }
bsc = { key = "${BSCSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
